"""M-EXAMINER-05: uncoupled Page-Wootters clock gives exact Schroedinger evolution for ANY clock; coupling breaks it.

Claim (finding 4, hardest question 1, EXAMINER-B/C), hbar = 1, energies in rad/s:
  If (H_C (x) 1 + 1 (x) H_S) Psi = 0 and psi(t) = (<t| (x) 1) Psi with <t| = <t0| exp(i H_C t) for any
  reference clock state |t0>, then i d/dt psi = H_S psi exactly (so psi(t) = exp(-i H_S t) psi(0)),
  whatever the clock spectrum (unequal spacing, degeneracy). A clock-system coupling H_CS breaks this.
Independent derivation (analytic): i d/dt <t| = i <t0| (i H_C) e^{iH_C t} = -<t| H_C, so
  i d/dt psi = -(<t| H_C (x) 1) Psi = (<t| (x) H_S) Psi = H_S psi, using the constraint.
Numeric test: random non-equally spaced degenerate clock, random H_S, random |t0>, random kernel vector.
Limit: coupling g -> 0 recovers exactness; Smith-Ahmadi coupling H_CS = -lam H_C H_S gives
  i psi' = H_S (1 - lam H_S)^{-1} psi (derived: H_C (1 - lam H_S) Psi = -H_S Psi).
"""
import sys
sys.path.insert(0, ".claude/skills/conundrum/scripts")
import numpy as np
import sympy as sp
from math_checks import inequality, identity, series, finish

rng = np.random.default_rng(7)


def expmh(H, t):
    w, V = np.linalg.eigh(H)
    return V @ np.diag(np.exp(-1j * w * t)) @ V.conj().T


def rand_herm(n):
    A = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    return (A + A.conj().T) / 2


dS = 3
HS = rand_herm(dS)
eS, VS = np.linalg.eigh(HS)
# clock: eigenvalues -eS[0] (twice, degenerate), -eS[1], -eS[2], plus two unrelated levels; random eigenbasis
Ec = np.array([-eS[0], -eS[0], -eS[1], -eS[2], 0.37, 2.9])
dC = len(Ec)
U, _ = np.linalg.qr(rng.normal(size=(dC, dC)) + 1j * rng.normal(size=(dC, dC)))
HC = U @ np.diag(Ec) @ U.conj().T


def kernel(J, tol=1e-9):
    u, s, vh = np.linalg.svd(J)
    return vh[s < tol * max(1, s.max())].conj().T


J = np.kron(HC, np.eye(dS)) + np.kron(np.eye(dC), HS)
K = kernel(J)
print("kernel dimension (uncoupled):", K.shape[1])
Psi = K @ (rng.normal(size=K.shape[1]) + 1j * rng.normal(size=K.shape[1]))
t0 = rng.normal(size=dC) + 1j * rng.normal(size=dC)


def cond(Psi, t, HC):
    bra = t0.conj() @ expmh(HC, -t)  # <t0| e^{+i H_C t}
    return np.kron(bra, np.eye(dS)) @ Psi


def max_dev(Psi, HC, Heff):
    p0 = cond(Psi, 0.0, HC)
    return max(np.abs(cond(Psi, t, HC) - expmh(Heff, t) @ p0).max() for t in np.linspace(0.1, 7.0, 25)) / np.abs(p0).max()


dev0 = max_dev(Psi, HC, HS)
print("uncoupled: max |psi(t) - e^{-iH_S t} psi(0)| / |psi(0)| =", dev0)
inequality(sp.Float(dev0), "<", sp.Float(1e-9))

# generic coupling: clock hopping (x) random system operator; need a nontrivial kernel -> shift J by an eigenvalue
X = rand_herm(dC)
Y = rand_herm(dS)
for g in (0.2, 1e-3, 0.0):
    Jg = J + g * np.kron(X, Y)
    w, V = np.linalg.eigh(Jg)
    k = np.argmin(np.abs(w))          # redefine the constraint as Jg - w_k so a null vector exists
    Psi_g = V[:, k]
    # compare with the uncoupled Schroedinger law generated by H_S shifted by the same constant w_k
    dev = max_dev(Psi_g, HC, HS - w[k] * np.eye(dS))
    print(f"coupling g = {g}: deviation from exp(-i (H_S - w) t) = {dev:.3e}")
    if g == 0.2:
        inequality(sp.Float(dev), ">", sp.Float(1e-3))
    if g == 0.0:
        inequality(sp.Float(dev), "<", sp.Float(1e-9))

# Smith-Ahmadi exactly solvable coupling
lam = 0.05
# coupled resonance: clock eigenvalue E with E (1 - lam e) + e = 0, i.e. E = -e/(1 - lam e)
Ec2 = np.array([-eS[0] / (1 - lam * eS[0])] * 2 + [-e / (1 - lam * e) for e in eS[1:]] + [0.37, 2.9])
HC = U @ np.diag(Ec2) @ U.conj().T
Jsa = np.kron(HC, np.eye(dS)) + np.kron(np.eye(dC), HS) - lam * np.kron(HC, HS)
Ksa = kernel(Jsa)
print("kernel dimension (Smith-Ahmadi):", Ksa.shape[1])
Psi_sa = Ksa @ (rng.normal(size=Ksa.shape[1]) + 1j * rng.normal(size=Ksa.shape[1]))
Heff = HS @ np.linalg.inv(np.eye(dS) - lam * HS)
dev_sa = max_dev(Psi_sa, HC, Heff)
dev_sa_naive = max_dev(Psi_sa, HC, HS)
print("Smith-Ahmadi: deviation from exp(-i H_S(1-lam H_S)^-1 t) =", dev_sa, "; from exp(-i H_S t) =", dev_sa_naive)
inequality(sp.Float(dev_sa), "<", sp.Float(1e-9))
inequality(sp.Float(dev_sa_naive), ">", sp.Float(1e-3))
# weak-coupling limit of the effective generator (scalar version)
e, l = sp.symbols("e l", positive=True)
series(e / (1 - l * e), "l", 0, 2, e + l * e**2)

raise SystemExit(finish())
